# chatbot-app-chart/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatbot-app-chart.fullname" . }}-secret
  labels:
    {{- include "chatbot-app-chart.labels" . | nindent 4 }}
type: Opaque
data:
  # The VLLM_API_KEY value from values.yaml will be base64 encoded here.
  # If apiKey in values.yaml is empty, this will result in an empty base64 string.
  VLLM_API_KEY: {{ .Values.llm.apiKey | b64enc | quote }}
